services:
  pg_altas:
    image: postgres:latest
    container_name: pg_altas
    environment:
      POSTGRES_DB: altas_sap
      POSTGRES_USER: altas
      POSTGRES_PASSWORD: altas123
    ports:
      - "5433:5432"
    volumes:
      - pg_altas_data:/var/lib/postgresql/data
volumes:
  pg_altas_data:
